### ISSUE TITLE
Can't load native library on Ubuntu (Scala/JVM app)

### ISSUE THREAD

**Issue by henricook** [hyperxpro/Brotli4j#51]
On my amd64 Ubuntu machine, running a scala/play framework application I get an error that the native library can't be found - do I need to install a system package to work with this library?

This is triggered by calling `ensureAvailability`

```
play.api.UnexpectedException: Unexpected exception[UnsatisfiedLinkError: Failed to load Brotli native library]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:258)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:95)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:203)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Caused by: java.lang.UnsatisfiedLinkError: Failed to load Brotli native library
	at play.filters.brotli.loader.BrotliNativeLoader.ensureAvailability(BrotliNativeLoader.java:78)
	at play.filters.brotli.Brotli.ensureAvailability(Brotli.java:69)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:42)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:50)
	at ai.henricook.common.PlayFiltersModule.httpFilters(PlayFiltersModule.scala:29)
	at ai.henricook.common.PlayFiltersModule.httpFilters$(PlayFiltersModule.scala:26)
	at ai.henricook.ApplicationModule.httpFilters(ApplicationModule.scala:195)
	at play.api.BuiltInComponents.httpRequestHandler(Application.scala:316)
	at play.api.BuiltInComponents.httpRequestHandler$(Application.scala:309)
	at play.api.BuiltInComponentsFromContext.httpRequestHandler$lzycompute(ApplicationLoader.scala:228)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.nio.file.Files.copy(Files.java:3035)
	at play.filters.brotli.loader.BrotliNativeLoader.<clinit>(BrotliNativeLoader.java:47)
	at play.filters.brotli.Brotli.<clinit>(Brotli.java:43)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:42)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:50)
	at ai.henricook.common.PlayFiltersModule.httpFilters(PlayFiltersModule.scala:29)
	at ai.henricook.common.PlayFiltersModule.httpFilters$(PlayFiltersModule.scala:26)
	at ai.henricook.ApplicationModule.httpFilters(ApplicationModule.scala:195)
	at play.api.BuiltInComponents.httpRequestHandler(Application.scala:316)
```

**Comment by hyperxpro** [comment]
Have you added Brotli4j dependency?

**Comment by henricook** [comment]
Hi @hyperxpro I have indeed. I'm actually using https://github.com/guardian/play-brotli-filter which specifies the dependency. I've tried specifying the dependency explicitly myself alongside what https://github.com/guardian/play-brotli-filter does as well.. Should that be all I need?

**Comment by slandelle** [comment]
> Should that be all I need?

No. See https://github.com/guardian/play-brotli-filter/blob/main/build.sbt#L65. This project only pulls the main brotli4j main module containing the compiled Java code. Then, it relies on [maven profiles](https://search.maven.org/artifact/com.aayushatharva.brotli4j/brotli4j/1.8.0/jar) to pull the correct additional module containing the native library for the current platform.

This strategy only works with maven, not with gradle nor sbt.

As a result, you have to add dependencies for the native libs modules you want explicitly in your build.
That's what we do in Gatling (we pull all of them), see https://github.com/gatling/gatling/blob/main/project/Dependencies.scala#L32-L36.

**Comment by henricook** [comment]
Amazing, thank you so much for the assistance both

**Comment by hyperxpro** [comment]
@slandelle is right.

I will add more detailed instructions for Gradle in README.md soon.

**Comment by henricook** [comment]
In case an SBT example helps at any point I've gone with a riff on the Gatling link. I wanted to only load the libs for the current arch.

```scala
val brotli4j = "com.aayushatharva.brotli4j"           % "brotli4j"                          % "1.8.0"

val brotli4jForArch = {
  val architecture = System.getProperty("os.arch").toLowerCase match {
    case arch if arch.startsWith("amd64") => "x86_64"
    case arch => arch
  }
  val name = System.getProperty("os.name").toLowerCase match {
    case osName if osName.startsWith("linux") => s"native-linux-$architecture"
    case osName if osName.startsWith("mac") => s"native-osx-$architecture"
    case osName if osName.startsWith("windows") => s"native-windows-$architecture"
    case _ => throw new Exception("Unknown platform when fetching Brotli dependency!")
  }
  brotli4j.withName(name)
}

libraryDependencies ++= Seq(
  brotli4j,
  brotli4jForArch
)

```
